name: cura
description: "CLI pour auditer la santÃ© des packages Dart."
version: 0.1.0
homepage: https://github.com/meragix/cura
repository: https://github.com/meragix/cura

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  http: ^1.1.0
  mason_logger: ^0.2.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  mocktail: ^1.0.0

executables:
  cura:
