name: cura
description: "CLI tool to audit Flutter/Dart package health, dependency scores, and maintenance status."
version: 0.6.1
homepage: https://github.com/meragix/cura
repository: https://github.com/meragix/cura/tree/main
issue_tracker: https://github.com/meragix/cura/issues
documentation: https://github.com/meragix/cura/tree/main/doc

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Core
  args: ^2.4.2

  # HTTP
  dio: ^5.9.1

  # Logger
  mason_logger: ^0.3.3

  # YAML
  yaml: ^3.1.2
  yaml_writer: ^2.0.0

  # Utils
  path: ^1.8.3
  pool: ^1.5.1
  cli_table: ^1.0.2

dev_dependencies:
  # Testing
  test: ^1.29.0
  mocktail: ^1.0.0

  # Linting
  lints: ^6.0.0

executables:
  cura:
